import LocalizedStrings from 'react-localization';

export const AppString = new LocalizedStrings({
    fa: {
        welcome: "!خوش آمدید",
        loginText: 'سامانه ارسال اعلان',
        loginTitle: 'ورود به حساب کاربری',
        username: 'نام کاربری',
        password: 'کلمه عبور',
        login: 'ورود',
        logout: 'بازگشت به پورتال',
        captchaPlaceHolder: 'متن را وارد کنید',
        loginToAccount: 'ورود به حساب کاربری',
        dashboard: 'پیشخوان',
        notifications: 'اعلان ها',
        setting: 'تنظیمات',
        searchText: ': جستجو بر اساس',
        serviceType: 'نوع سرویس',
        sender: 'ارسال کننده',
        dateRange: ': بازه زمانی',
        to: 'تا',
        search: 'جستجو',
        notifTitle: 'عنوان پیام',
        notifText: 'متن پیام',
        totalNotifs: 'روند ارسال',
        sendedNotif: 'ارسال شده',
        sendPercentage: 'درصد ارسال',
        status: 'وضعیت',
        sendDateRange: 'بازه زمانی ارسال',
        sendTimeRange: 'بازه ساعتی ارسال',
        editDelete: 'حذف/ویرایش',
        title: 'عنوان',
        text: 'متن',
        filter: 'فیلتر',
        filterAccordionText: 'جهت تعیین گروه هدف، صنف،نوع نرم افزار،نام شرکت پرداخت و ...',
        appType: 'نوع نرم افزار',
        businessCategory: 'صنف',
        psp: 'شرکت پرداخت',
        province: 'استان',
        merchantType: 'نوع مشتری',
        residencyType: 'ملیت',
        terminalType: 'نوع ترمینال',
        terminalNumber: 'شماره ترمینال',
        nationalCode: 'کد ملی',
        schedule: 'زمانبندی',
        scheduleAccordionText: 'جهت تعیین بازه زمانی ارسال پیام',
        sendNotifDateRange: ': بازه زمانی ارسال پیام',
        sendNotifTimeRange: ': بازه ساعتی ارسال پیام',
        fromDate: ': * از تاریخ ',
        fromTime: ': * از ساعت',
        toDate: ': * تا تاریخ',
        toTime: ': * تا ساعت',
        submit: 'ثبت',
        edit: 'ویرایش',
        cancel: 'لغو',
        delete: 'حذف',
        pause: 'توقف',
        resume: 'ادامه',
        ServiceType: 'ServiceType',
        AppType: 'AppType',
        BusinessCategory: 'BusinessCategory',
        Psp: 'PSP',
        Province: 'Province',
        MerchantType: 'MerchantType',
        ResidencyType: 'ResidencyType',
        TerminalType: 'TerminalType',
        Status: 'MsgStatus',
        Sender: 'users',
        ScheduleChoice: 'ScheduleChoice',
        smsTitleHintText: '(تعداد کاراکتر مجاز: 30 عدد)',
        emailTitleHintText: '(تعداد کاراکتر مجاز: 10 الی 100 عدد)',
        notificationTitleHintText: '(تعداد کاراکتر مجاز: 10 الی 30 عدد)',
        internalNotificationTitleHintText: '(تعداد کاراکتر مجاز: 10 الی 30 عدد)',
        smsBodyHintText: '(تعداد کاراکتر مجاز: 10 الی 160 عدد)',
        emailBodyHintText: '(تعداد کاراکتر مجاز: 10 الی 2000 عدد)',
        notificationBodyHintText: '(تعداد کاراکتر مجاز: 10 الی 50 عدد)',
        internalNotificationBodyHintText: '(تعداد کاراکتر مجاز: 10 الی 500 عدد)',
        terminalNumberErrorHint: '(تعداد ارقام مجاز : 8 عدد)',
        terminalNumberErrorMsg: 'شماره ترمینال نامعتبر',
        nationalCodeErrorMsg: 'کد ملی نامعتبر',
        emptyFieldErrMsg: 'پر کردن این فیلد الزامی است',
        minTitleCharacterErrMsg: 'حداقل 10 کاراکتر وارد کنید',
        minBodyCharacterErrMsg: 'حداقل 10 کاراکتر وارد کنید',
        dateRangeErrMsg: 'بازه تاریخی خارج از محدوده است',
        timeRangeErrMsg: 'بازه زمانی خارج از محدوده است',
        timeRangeMinHoursErrMsg: 'بازه زمانی انتخابی کمتر از یک ساعت می باشد',
        tableServiceType: 'serviceType',
        tableTitle: 'title',
        tableBody: 'body',
        tableTotalCount: 'totalCount',
        tableSuccessCount: 'successCount',
        tablePercent: 'percent',
        tableStatus: 'status',
        tableSender: 'userId',
        tableStartTime: 'tableStartTime',
        tableEndTime: 'tableEndTime',
        tableStartDate: 'tableStartDate',
        tableEndDate: 'tableEndDate',
        tableTimeRange: 'timeRange',
        tableStartDateSend: 'startDateSend',
        tableEndDateSend: 'endDateSend',
        tableHandleEditNotif: 'edit',
        tableHandleCancelNotif: 'cancel',
        tableHandleDeleteNotif: 'delete',
        tableHandlePauseResumeNotif: 'pauseResume',
        successCreateNotifDialogText: '.پیام شما با موفقیت ثبت شد',
        successEditNotifDialogText: '.پیام شما با موفقیت ویرایش شد',
        successUpdateSettingDialogText: '.تنظیمات با موفقیت اعمال شد',
        cancelNotifWarningDialogText: 'آیا از لغو ارسال پیام ها اطمینان دارید ؟',
        deleteNotifWarningDialogText: 'آیا از حذف پیام ها اطمینان دارید ؟',
        editNotifWarningDialogText: '! امکان ویرایش پیام در حال ارسال وجود ندارد',
        accept: 'تایید',
        close: 'بستن',
        decline: 'انصراف',
        successDeleteMsg: 'پیام شما با موفقیت حذف شد',
        successCancelMsg: 'پیام شما با موفقیت لغو شد',
        failDeleteMsg: '!پیام در حال ارسال است، امکان حذف پیام وجود ندارد',
        failCancelMsg: '!پیام در حال ارسال است، امکان لغو ارسال پیام وجود ندارد',
        failEditMsg: '!پیام در حال ارسال است، امکان ویرایش پیام وجود ندارد',
        settingActiveServiceTitle: 'فعال / غیر فعال نمودن سرویس ها',
        settingRequestsTitle: 'تعیین وضعیت درخواست ها',
        settingIpConfigTitle: 'ماشین دریافت/ارسال کننده درخواست ها',
        settingLoadMasterIp: 'ماشین دریافت کننده وضعیت درخواست ها',
        settingSaveMasterIp: 'ماشین ارسال کننده درخواست ها',
        smsService: 'سرویس پیامک',
        emailService: 'سرویس ایمیل',
        alarmService: 'سرویس پیام داخلی',
        activeLoadMaster: ' به روزرسانی وضعیت درخواست ها',
        activeSaveMaster: 'ارسال درخواست ها',
        notificationService: 'سرویس نوتیفیکیشن',
        submitSettingButtonText: 'اعمال تنظیمات',
        timeChoose: ' : انتخاب زمانبندی',
        yesterday: 'دیروز',
        lastWeek: 'هفته گذشته',
        lastMonth: 'ماه گذشته',
        dashboardTotalCount: ' تعداد کل اعلان های ارسال شده',
        sms: 'پیامک',
        email: 'ایمیل',
        notification: 'نوتیفیکیشن',
        alarm: 'پیام داخلی',
        count: 'تعداد',
        smsGaugeText: 'پیامک',
        emailGaugeText: 'ایمیل',
        notificationGaugeText: 'نوتیفیکیشن',
        alarmGaugeText: 'پیام داخلی',
        gaugeTitle: 'میزان پیشرفت درخواست ها',
        dashboardSearchErrorMsg: 'داده ای در بازه تاریخی مورد نظر وجود ندارد',
        startDate: 'شروع',
        endDate: 'پایان',
        startTime: 'شروع',
        endTime: 'پایان',
        noData: 'داده ای برای نمایش وجود ندارد',
        ascendingText: 'مرتب سازی صعودی',
        descendingText: 'مرتب سازی نزولی',
        sortClearText: 'حذف مرتب سازی',
        notFound: '404 !  متاسفانه صفحه ای یافت نشد',
        invalidLoadMasterIpError: '! ماشین دریافت کننده موجود نمی باشد',
        invalidSaveMasterIpError: '!ماشین ارسال کننده موجود نمی باشد',
        noPermissionToLogin:'دسترسی ورود به سیستم برای شما یافت نشد'

    },
    // en: {
    //     welcome: "welcome!",
    //     loginText: 'welcome to shaparak portal',
    //     loginTitle : 'login to account'
    // },
});