import LocalizedStrings from 'react-localization';

export const AppString = new LocalizedStrings({
    fa: {
        username: 'نام کاربری',
        firstName: 'نام',
        lastName: 'نام خانوادگی',
        phoneNumber: 'شماره موبایل',
        password: 'رمز عبور',
        repeatPassword: 'تکرار رمز',
        Username: 'username',
        FirstName: 'firstName',
        LastName: 'lastName',
        PhoneNumber: 'phoneNumber',
        Password: 'password',
        RepeatPassword: 'repeatPassword',
        login: 'ورود',
        register: 'ثبت نام',
        Register: 'ثبت',
        back: 'بازگشت',
        account: 'حساب کاربری',
        addEvent: 'ایجاد رویداد',
        firstNameValidationText: 'نام خود را وارد نمایید',
        lastNameValidationText: 'نام خانوادگی خود را وارد نمایید',
        usernameValidationText: 'نام کاربری خود را وارد نمایید',
        phoneNumberValidationText: 'شماره تلفن خود را وارد نمایید',
        passwordValidationText: 'رمز عبور خود را وارد نمایید',
        minCharValidationText: 'حداقل دو کاراکتر وارد نمایید',
        minUsernamePassCharValidationText: 'حداقل پنج کاراکتر وارد نمایید',
        minPhoneNumberCharValidationText: 'شماره همراه نامعتبر است',
        repeatPassNotMatchValidationText: 'رمز عبور ها یکسان نیستند',
        home: 'خانه',
        notAvailable: 'موجود نیست',
        eventType: 'نوع رویداد',
        eventName: 'نام رویداد',
        choose: 'انتخاب نمایید...',
        upload: 'بارگذاری',
        eventPic: ' : تصویر',
        dateRange: ': بازه زمانی',
        to: 'تا',
        shareEvent: 'اشتراک گذاری رویداد',
        saveEvent: 'ذخیره رویداد'
    },
});